### ISSUE TITLE
Is there a way to change the model?

### ISSUE THREAD

**Issue by dillfrescott** [yusufcanb/tlm#14]
Id like to change it to dolphincoder because its newer

**Comment by dillfrescott** [comment]
I just used notepad++ on windows (or ack on linux) to search for `codellama` and `codellama:7b` and change them to `dolphincoder` and then did `go build`.

**Comment by dillfrescott** [comment]
seems to be working

**Comment by yusufcanb** [comment]
`tlm` should be an end product where user should be isolated from the underlying model. So, it is me and other contributors responsibility to find the most efficient and low-resource LLM. 

Thanks for trying it out. I will also check the `dolphincoder` as well.

**Comment by dillfrescott** [comment]
Okay!
