### ISSUE TITLE
Problem with explain?

### ISSUE THREAD

**Issue by oderwat** [yusufcanb/tlm#24]
```
>$ tlm suggest "showing the current time as unix time"
┃ > Thinking... (1.343003842s)
┃ > date +%s
┃ > Explaining...

Error during generation: model 'tlm:-e' not found, try pulling it first
```

Setup is "bash" even when on mac, because I use bash and not zsh. Could it have to do with that?

**Comment by yusufcanb** [comment]
Thanks for reporting the issue. I've recently refactored modelfile naming convention and try to make features more modulerized and it seems I forget to add version to Explain construction inside Suggest.

https://github.com/yusufcanb/tlm/commit/0763640b56123c2e5c071a5a29db228ccf0fe5f2#diff-45bd16282ab0291e55894f364d34f3c841c77e708fc930c70b84e12b939b9523L105

Thanks again, please re-build or re-install with `go install github.com/yusufcanb/tlm@latest`
