### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by doduythao** [yusufcanb/tlm#31]
**Describe the bug**
curl -fsSL https://raw.githubusercontent.com/yusufcanb/tlm/1.1/install.sh | sudo -E bash

**Console Output**
>>> Downloading tlm version 1.1 for linux/amd64...
curl: (23) Failure writing output to destination
ERROR Download failed. Please check your internet connection and try again.

**tlm Version**
tlm on Ubuntu

**Platform Information (please complete the following information):**
tlm on Ubuntu

**Additional context**
tlm on Ubuntu

**Comment by yusufcanb** [comment]
Can you please check your internet connection on the Ubuntu machine and try again as console output suggests?
